stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.57.0-jammy
  
  script:
    - npm ci
    - npx playwright test

  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 30 days